"""empty message

Revision ID: 34a956c73107
Revises: 
Create Date: 2024-06-21 10:01:38.431766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34a956c73107'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customername', sa.String(length=50), nullable=True),
    sa.Column('customeremail', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('book')
    op.drop_table('employee')
    op.drop_table('department')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('productname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('productunit', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('department',
    sa.Column('dept_no', mysql.CHAR(length=4), nullable=False),
    sa.Column('dept_name', mysql.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('dept_no'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('employee',
    sa.Column('emp_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('gender', mysql.CHAR(length=1), nullable=False),
    sa.Column('hire_date', sa.DATE(), nullable=False),
    sa.Column('salary', mysql.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('dept_no', mysql.CHAR(length=4), nullable=False),
    sa.ForeignKeyConstraint(['dept_no'], ['department.dept_no'], name='employee_ibfk_1'),
    sa.PrimaryKeyConstraint('emp_no'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('book',
    sa.Column('bookid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booktitle', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bookauthor', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('publisher', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('bookid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('customers')
    # ### end Alembic commands ###
